import Head from 'next/head'
import { useEffect, useState } from 'react'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Projects from '../components/Projects'
import Summary from '../components/Summary'
import Urls from '../components/Urls'

export default function Home() {
  const [data, setData] = useState(null)
  const [isLoading, setIsLoading] = useState(false)
  const url = 'https://justfields.com/project/aB64KQvW/json'

  useEffect(() => {
    setIsLoading(true)
    fetch(url)
      .then(res => res.json())
      .then(data => {
        setData(data.home)
        setIsLoading(false)
      })
  }, [])


  isLoading && <div>Loading...</div>
  !data && <div>No data</div>

  console.log('data', data)

  return (
    <div>
      <Head>
        <title>kdrgny.online | Kadir Günay Online CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto max-w-6xl p-3 my-auto bg-opacity-80 bg-gray-100 border-4 border-gray-600 print:border-0 page print:max-w-letter print:max-h-letter print:mx-0 print:my-o lg:h-letter md:max-w-letter md:h-letter xsm:p-8 sm:p-9 md:p-16 lg:mt-6 rounded-2xl print:bg-white">
        <Header data={data} />
        <div className="flex gap-10 mt-6">
          <div className="w-1/3">
            <div className="flex flex-col gap-4">
              <Urls data={data?.urls} />
              <Summary data={data?.summary} />
              <Experience data={data?.experience} />
              <Projects data={data?.projects} />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
