import Head from 'next/head'
import { useEffect, useState } from 'react'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import Summary from '../components/Summary'
import Urls from '../components/Urls'
import { useTheme } from 'next-themes'
import Footer from '../components/Footer'
import Certificates from '../components/Certificates'
import Loading from '../components/Loading'

export default function Home() {
  const [data, setData] = useState(null)
  const [isLoading, setIsLoading] = useState(false)
  const url = process.env.JSON_URL

  const { theme, setTheme } = useTheme('light')

  useEffect(() => {
    setIsLoading(true)
    fetch(url)
      .then(res => res.json())
      .then(data => {
        setData(data.home)
        setIsLoading(false)
      })
  }, [])


  return (
    isLoading ? <div className='flex items-center justify-center min-h-screen'>
      <Loading />
    </div> : !data ? <div>No data</div> : (
      <div className='relative flex flex-col min-h-screen items-center mx-auto px-5 xl:px-0'>
        <Head>
          <title>kdrgny.online | Frontend Developer Kadir Günay Online CV</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="fixed top-4 right-4">
          <button
            onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            type="button"
            className="text-gray-100 bg-gray-400 dark:text-gray-100 hover:bg-gray-700 focus:outline-none rounded-lg text-sm p-2.5 transition duration-500 ease-in-out"
          >
            <svg
              className={`w-6 h-6 ${theme === 'dark' ? '' : 'hidden'}`}
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
                fillRule="evenodd"
                clipRule="evenodd"
              ></path>
            </svg>

            <svg
              className={`w-6 h-6 ${theme === 'dark' ? 'hidden' : ''}`}
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"
              ></path>
            </svg>
          </button>
        </div>
        <div className="container mx-auto max-w-6xl xl:px-10 px-5 py-5 bg-gray-100 dark:bg-black border-4 border-gray-500 dark:border-gray-300 shadow-2xl rounded-2xl my-10">
          <Header data={data} />
          <div className="flex flex-col xl:flex-row xl:gap-10 gap-5 mt-6">
            <div className="xl:w-1/3 w-full">
              <div className="flex flex-col gap-4 last:border-b-0">
                <Urls data={data?.urls} />
                <Summary data={data?.summary} />
                <Projects data={data?.projects} />
                <Skills data={data?.skills} />
              </div>
            </div>
            <div className="xl:w-2/3 w-full">
              <div className="flex flex-col gap-4">
                <Experience data={data?.experience} />
                <Certificates data={data?.certificates} />
              </div>
            </div>
          </div>
        </div>
        <Footer />

      </div>
    )
  )
}
